### ISSUE TITLE
Analyze only United States data

### ISSUE THREAD

**Issue by nashmakh** [UBC-MDS/DSCI532-Group16#13]
We will need to remove observations from other countries and make this analysis specific to United States since majority of the data is USA data and using the USA GeoJSON data will work better for our dashboard.

**Comment by micahkwok** [comment]
Sure, I think that is a good idea. Maybe we should make a note of it somewhere for the TA in case they don't know this change since our initial design image shows a global map.

**Comment by nashmakh** [comment]
Added a comment in reflections doc.
