### ISSUE TITLE
Joel Suggestions for Improvement

### ISSUE THREAD

**Issue by micahkwok** [UBC-MDS/DSCI532-Group16#26]
Joel dropped into our lab session in week 3 and gave some suggestions, summarized below.

- On the map, the states that are in white (no data) are a bit confusing. Maybe change color to grey to indicate that it's N/A
- Add space between the checkbox and filter
- If we're doing only one tab, don't have a tab up there (fixed as we will probably do 2 tabs)
- Have comparisons in plots (potentially facetting by gender etc.)

**Comment by nashmakh** [comment]
Most of the feedback has been implemented this week, specifically the first 3 bullet points. The last suggestion with respect to plots will be addressed next week before milestone 4.
